# Generated by Django 2.2.11 on 2020-03-20 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20200320_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
